services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app # mount source code
      - /app/node_modules # keep node_modules inside container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # required for hot reload in Docker
    depends_on:
      - backend
