services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: db.postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=db.postgres
      - DB_USER=user
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app # mount source code
      - /app/node_modules # keep node_modules inside container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # required for hot reload in Docker
    depends_on:
      - backend

volumes:
  postgres_data:
