# Generated by Django 4.2.25 on 2025-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.JSONField(default=dict)),
                ('year', models.IntegerField(default=2025)),
                ('month', models.PositiveSmallIntegerField(default=11)),
            ],
        ),
    ]
