# Generated by Django 4.2.25 on 2025-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizedShift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedshift',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
