# Generated by Django 4.2.25 on 2025-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
