# Generated by Django 5.2.4 on 2025-10-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_shiftrequirement_month_shiftrequirement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='availability_calendar',
            field=models.JSONField(default=dict),
        ),
    ]
