# Generated by Django 5.2.4 on 2025-10-18 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_managerrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerrequirement',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='managerrequirement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='managerrequirement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managerrequirement',
            name='hard_rule',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='managerrequirement',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerrequirement',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managerrequirement',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='managerrequirement',
            unique_together={('manager', 'year', 'month')},
        ),
    ]
