"""Pyomo abstract model for shift scheduling.

Refactored from the former ``optimizer/model_def.py``. Key differences that make
it work as part of the real pipeline rather than a standalone demo:

- ``D`` (days) and ``S`` (shifts) are runtime ``Set``s populated from instance
  data instead of a hardcoded 7-day week / 2 fixed shift ids. The canonical
  contract is: days are ISO date strings of the target month, shifts are the
  string labels ``"morning"`` / ``"evening"``.
- ``M_AVAIL[e, d, s]`` is the binary availability matrix (from each employee's
  O/X calendar) and is enforced as a *hard constraint*: an employee can never be
  assigned to a slot they marked unavailable.
- The weekly constraints (min one shift / week, <= 40h / week) are expressed over
  ISO-week groupings of the month's dates, passed in as the ``week_of`` param and
  the ``W`` set, instead of assuming a single 7-day horizon.
- ``Z1`` / ``Z2`` are mutable objective weights (default 1) so the evaluator can
  generate several candidate schedules with different ED/EE emphasis and pick the
  best, matching the README's "generate multiple, choose best" design.
"""

from pyomo.environ import (
    AbstractModel,
    Set,
    Param,
    Var,
    Binary,
    Reals,
    Expression,
    Objective,
    minimize,
    value,
    sqrt,
)

# constant (preventing divide-by-zero error in cosine-similarity denominators)
EPS = 1e-4


def build_model():
    """Return a fresh ``AbstractModel``.

    A new instance is built per call so the engine can create independent
    instances without shared mutable state.
    """
    model = AbstractModel()

    # Sets (all populated from instance data)
    model.E = Set()                 # Employees (usernames)
    model.D = Set()                 # Days (ISO date strings of the month)
    model.S = Set()                 # Shifts ("morning", "evening")
    model.W = Set()                 # ISO week ids spanned by the month

    # Parameters
    model.n = Param()                                   # No. of employees
    model.m = Param(initialize=2)                       # No. of shifts per day
    model.workers_per_shift = Param(initialize=2)       # required workers per shift
    model.time_open = Param()
    model.time_close = Param()
    model.week_of = Param(model.D, within=Reals)        # date -> week id

    # Objective weights (mutable so the evaluator can vary them)
    model.Z1 = Param(initialize=1, mutable=True)        # weight on ED loss
    model.Z2 = Param(initialize=1, mutable=True)        # weight on EE loss

    def business_hours_rule(model):
        time_open = model.time_open.value
        time_close = model.time_close.value
        if time_close > time_open:
            return time_close - time_open
        return time_close - time_open + 24
    model.BusinessHours = Param(initialize=business_hours_rule)

    def shift_hours_rule(model):
        n_shift = model.m.value
        h_hours = model.BusinessHours()
        return int(h_hours / n_shift)
    model.ShiftHours = Param(initialize=shift_hours_rule)

    # Matrices generated by the LLM extractor + the availability calendar
    model.M_LLM_ED = Param(model.E, model.D, model.S, domain=Reals, default=0)
    model.M_LLM_EE = Param(model.E, model.E, domain=Reals, default=0)
    model.M_AVAIL = Param(model.E, model.D, model.S, domain=Reals, default=0)

    # Decision variables
    model.A = Var(model.E, model.D, model.S, domain=Binary)
    model.M_sugg_EE = Var(model.E, model.E, domain=Reals, bounds=(-1, 1))

    # ----------------------------- Constraints -----------------------------
    @model.Constraint(model.E, model.D, model.S)
    def availability_rule(model, e, d, s):
        # Cannot assign an employee to a slot they are not available for.
        return model.A[e, d, s] <= model.M_AVAIL[e, d, s]

    @model.Constraint(model.D, model.S)
    def workers_per_shift_rule(model, d, s):
        # Each shift must be staffed by the required number of workers.
        return sum(model.A[e, d, s] for e in model.E) == model.workers_per_shift

    @model.Constraint(model.E, model.W)
    def minimum_shift_per_week(model, e, w):
        # Each worker should work at least one shift per week they could work.
        days_in_week = [d for d in model.D if value(model.week_of[d]) == w]
        return sum(model.A[e, d, s] for d in days_in_week for s in model.S) >= 1

    @model.Constraint(model.E, model.W)
    def fourty_hours_per_week(model, e, w):
        # Each worker should work no more than 40 hours per week.
        h_shift = model.ShiftHours.value
        days_in_week = [d for d in model.D if value(model.week_of[d]) == w]
        return sum(model.A[e, d, s] * h_shift
                   for d in days_in_week for s in model.S) <= 40

    @model.Constraint(model.E, model.D)
    def eight_hours_per_day_rule(model, e, d):
        # Each worker should work no more than 8 hours per day.
        h_shift = model.ShiftHours.value
        return sum(model.A[e, d, s] for s in model.S) * h_shift <= 8

    # -------------------- Objective function & supplements --------------------
    # The objective math is preserved from the original model_def.py.
    # ED Matrix - element-wise difference
    def ED_Element_Rule(m):
        return (1 / (len(m.E) * len(m.D) * len(m.S))) * sum(
            (m.A[e, d, s] - m.M_LLM_ED[e, d, s])
            for e in m.E for d in m.D for s in m.S
        )
    model.ED_Element_diff = Expression(rule=ED_Element_Rule)

    # ED Matrix - employee-wise cosine similarity
    def ED_DotProduct_Per_Employee_Rule(m, e):
        return sum(m.A[e, d, s] * m.M_LLM_ED[e, d, s] for d in m.D for s in m.S)
    model.ED_DotProduct_Per_Employee = Expression(
        model.E, rule=ED_DotProduct_Per_Employee_Rule)

    def ED_L2Norm_Employee_Rule(m, e):
        return sqrt(sum(m.A[e, d, s] ** 2 for d in m.D for s in m.S)) * \
            sqrt(sum(m.M_LLM_ED[e, d, s] ** 2 for d in m.D for s in m.S))
    model.ED_Employee_denominator = Expression(
        model.E, rule=ED_L2Norm_Employee_Rule)

    def ED_Employee_CosSim_Rule(m, e):
        return m.ED_DotProduct_Per_Employee[e] / (m.ED_Employee_denominator[e] + EPS)
    model.ED_Employee_diff = Expression(model.E, rule=ED_Employee_CosSim_Rule)

    # ED Matrix - whole matrix cosine similarity
    def ED_DotProduct_Rule(m):
        return sum(
            m.A[e, d, s] * m.M_LLM_ED[e, d, s]
            for e in m.E for d in m.D for s in m.S
        )
    model.ED_DotProduct = Expression(rule=ED_DotProduct_Rule)

    def L2Norm_A_Rule(m):
        sum_of_square = sum(m.A[e, d, s] ** 2 for e in m.E for d in m.D for s in m.S)
        return sqrt(sum_of_square)
    model.L2Norm_A = Expression(rule=L2Norm_A_Rule)

    def L2Norm_M_LLM_ED_Rule(m):
        sum_of_square = sum(
            (m.M_LLM_ED[e, d, s]) ** 2
            for e in m.E for d in m.D for s in m.S
        )
        return sqrt(sum_of_square)
    model.L2Norm_M_LLM_ED = Expression(rule=L2Norm_M_LLM_ED_Rule)

    def ED_CosSim_Rule(m):
        return m.ED_DotProduct / (m.L2Norm_A * m.L2Norm_M_LLM_ED + EPS)
    model.ED_diff = Expression(rule=ED_CosSim_Rule)

    def ED_Loss_Rule(m):
        return m.ED_Element_diff + sum(m.ED_Employee_diff[e] for e in m.E) + m.ED_diff
    model.ED_Loss = Expression(rule=ED_Loss_Rule)

    # EE Matrix - element-wise difference
    def EE_Element_Rule(m):
        return (1 / (len(m.E) * len(m.E))) * sum(
            (m.M_sugg_EE[e, e_] - m.M_LLM_EE[e, e_])
            for e in m.E for e_ in m.E
        )
    model.EE_Element_diff = Expression(rule=EE_Element_Rule)

    # EE Matrix - employee-wise cosine similarity
    def EE_DotProduct_Per_Employee_Rule(m):
        return sum(
            m.M_sugg_EE[e, e_] * m.M_LLM_EE[e, e_]
            for e in m.E for e_ in m.E
        )
    model.EE_DotProduct_Per_Employee = Expression(
        rule=EE_DotProduct_Per_Employee_Rule)

    def EE_L2Norm_Employee_Rule(m, e):
        return sqrt(sum(m.M_sugg_EE[e, e_] ** 2 for e_ in m.E)) * \
            sqrt(sum(m.M_LLM_EE[e, e_] ** 2 for e_ in m.E))
    model.EE_Employee_denominator = Expression(
        model.E, rule=EE_L2Norm_Employee_Rule)

    def EE_Employee_CosSim_Rule(m, e):
        return m.EE_DotProduct_Per_Employee / (m.EE_Employee_denominator[e] + EPS)
    model.EE_Employee_diff = Expression(model.E, rule=EE_Employee_CosSim_Rule)

    # EE Matrix - whole matrix cosine similarity
    def EE_DotProduct_Rule(m):
        return sum(
            m.M_sugg_EE[e, e_] * m.M_LLM_EE[e, e_]
            for e in m.E for e_ in m.E
        )
    model.EE_DotProduct = Expression(rule=EE_DotProduct_Rule)

    def L2Norm_M_sugg_EE_Rule(m):
        sum_of_square = sum(
            m.M_sugg_EE[e, e_] ** 2
            for e in m.E for e_ in m.E
        )
        return sqrt(sum_of_square)
    model.L2Norm_M_sugg_EE = Expression(rule=L2Norm_M_sugg_EE_Rule)

    def L2Norm_M_LLM_EE_Rule(m):
        sum_of_square = sum(
            (m.M_LLM_EE[e, e_]) ** 2
            for e in m.E for e_ in m.E
        )
        return sqrt(sum_of_square)
    model.L2Norm_M_LLM_EE = Expression(rule=L2Norm_M_LLM_EE_Rule)

    def EE_CosSim_Rule(m):
        return m.EE_DotProduct / (m.L2Norm_M_sugg_EE * m.L2Norm_M_LLM_EE + EPS)
    model.EE_diff = Expression(rule=EE_CosSim_Rule)

    def EE_Loss_Rule(m):
        return m.EE_Element_diff + sum(m.EE_Employee_diff[e] for e in m.E) + m.EE_diff
    model.EE_Loss = Expression(rule=EE_Loss_Rule)

    # Objective: weighted sum of the ED and EE losses.
    @model.Objective(sense=minimize)
    def minimize_oss(m):
        return m.Z1 * m.ED_Loss + m.Z2 * m.EE_Loss

    return model
